Repository liruipeng/ml2, pull requests merged in 2025-06, with the labels that each got.

#21 Remove verbose from `ReduceLRonPlateau`
  tony/test_poisson.py
Labels: bug

#16 Add plotting for frequency transform
  .gitignore
  pinn/pinn_1d.py
  pinn/utils.py
Labels: enhancement, experiment

#34 Add package dependency
  .github/workflows/main.yml
  .gitignore
  pyproject.toml
Labels: enhancement

#22 Implementation on trigonometric activation and Chebyshev features
  tony/README.md
  tony/config/poisson.py
  tony/model/bc.py
  tony/model/nn.py
  tony/run.tuo
  tony/test_poisson.py
  tony/writing/note.tex
  tony/writing/poisson.tex
Labels: enhancement
